SELECT 
	p.PICKUP_LOCATION AS 'Delivery Location',
    COUNT(d.DELIVERY_ID) AS 'Total Completed Deliveries',
    MONTHNAME(d.DELIVERY_DATE) AS 'Month',
    YEAR(d.DELIVERY_DATE) AS 'Year',
    RANK() OVER (ORDER BY COUNT(d.DELIVERY_ID) DESC) AS Location_Rank
FROM Deliveries d
JOIN Pickups p ON d.ORDER_ID = p.ORDER_ID
WHERE d.DELIVERY_STATUS = 'Delivered'
	AND YEAR(d.DELIVERY_DATE) = YEAR(CURDATE())
    AND MONTH(d.DELIVERY_DATE) = MONTH(CURDATE())
GROUP BY p.PICKUP_LOCATION
ORDER BY COUNT(d.DELIVERY_ID) DESC;