CREATE TABLE Deliveries (
	DELIVERY_ID DECIMAL (10,0) PRIMARY KEY,
    ORDER_ID DECIMAL (10,0) NOT NULL,
    DELIVERY_TYPE CHAR (15) NOT NULL,
    DELIVERY_STATUS CHAR (15) DEFAULT 'Pending',
    DRIVER_ID DECIMAL (10,0) NOT NULL,
    PAYMENT CHAR (15) NOT NULL,
    EST_DELIVERY_TIME TIME,
    ACT_DELIVERY_TIME TIME,
    DELIVERY_FEE INT (5) NOT NULL,
    DELIVERY_DATE DATE
    );