-- driver table
CREATE TABLE Drivers (
    DRIVER_ID DECIMAL(10, 0) PRIMARY KEY,
    DRIVER_LASTNAME VARCHAR(20) NOT NULL,
    DRIVER_FIRSTNAME VARCHAR(20) NOT NULL,
    DRIVER_CONTACT DECIMAL(10, 0),
    DRIVER_LICENCE CHAR(13) NOT NULL,
    STATUS CHAR(10) DEFAULT 'Available',
    SHIFT TIME
);