-- SUCCESSFUL PICKUP
UPDATE Pickups
SET STATUS = 'Completed', PAYMENT_METHOD = ?
WHERE ORDER_ID = ?;

-- FAILED PICKUP
UPDATE Pickups 
SET STATUS = 'Failed'
WHERE ORDER_ID = ?;

-- GETTING PICKUP DEETS FOR VERIFICATION
SELECT ORDER_ID, CUSTOMER_ID, STATUS, PICKUP_LOCATION
FROM Pickups
WHERE ORDER_ID = ?;