USE pickups;

CREATE TABLE Pickups (
ORDER_ID DECIMAL (10, 0) PRIMARY KEY,
ORDER_TYPE CHAR (15),
STATUS CHAR (10),
PICKUP_LOCATION VARCHAR (50),
PICKUP_DATE DATE,
PICKUP_SERVICE VARCHAR (20),
PAYMENT_METHOD CHAR (15) /*,
FOREIGN KEY (CUSTOMER_ID) REFERENCES Customers(CUSTOMER_ID) // Add when Customer table is ready !
 */
);